name: Build and Publish
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies ui
        run: node --version && npm --version && cd ui && npm install
      - name: Install dependencies root
        run: npm install
      - name: Build 
        run: npm run build
      - name: run test
        run: npm run test  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/appointments:${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/appointments:latest

