name: Build and Publish
on:
  push:
    branches:
      - master
      - 'release-*'
      - BAH-2296
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies ui
        run:  cd ui && npm install
      - name: Install dependencies root
        run: npm install
      - name: run test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Package dist
        run: cd dist && zip -r ../appointments.zip .
      - name: Upload appointments zip
        uses: actions/upload-artifact@v3
        with:
          name: appointments.zip
          path: appointments.zip

  docker-build-publish:
    name: Docker Build Publish
    runs-on: ubuntu-latest
    needs: [build]
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - uses: actions/checkout@v2
      - name: Set artifact version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - uses: actions/download-artifact@v3
        with:
          name: appointments.zip
          path: .
      - name: Unzip appointments.zip
        run: unzip -d dist appointments.zip
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/appointments:${{env.ARTIFACT_VERSION}},bahmni/appointments:latest
      - name: Helm - Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: Bahmni/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/appointments/ && cp appointments-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/appointments/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of bahmni-web-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages

  rpm-build-publish:
    name: RPM Build Publish
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Set artifact version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - uses: actions/download-artifact@v3
        with:
          name: appointments.zip
          path: package/rpm/resources
      - name: Setup Java 8 for Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Build RPM
        run: |
          cd package/rpm
          export version=$(awk -F- '{print $1}' <<< ${{env.ARTIFACT_VERSION}})
          export release=$(awk -F- '{print $2}' <<< ${{env.ARTIFACT_VERSION}})
          ./gradlew -Pversion=$version -Prelease=$release clean buildRpm
      - uses: actions/upload-artifact@v3
        with:
          name: appointments-rpm
          path: package/rpm/build/distributions/*.rpm

