name: Build and Publish
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  repository_dispatch:
    types: ["default-config-trigger"]

env:
  APPOINTMENTS_VERSION: v2

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies ui
        run: node --version && npm --version && cd ui && npm install
      - name: Install dependencies root
        run: npm install
      - name: Build 
        run: npm run build
      - name: run test
        run: npm run test  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: stavtnameh/appointments:${{env.APPOINTMENTS_VERSION}}-${{github.run_number}},stavtnameh/appointments-v2:latest

