name: Build and Upload
on:
  push:
    branches:
      - temporary_build_branch
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies ui
        run:  cd ui && npm install
      - name: Install dependencies root
        run: npm install
      - name: run test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist/ # or path/to/artifact